name: Occultum
url: https://occultum.github.io
description: A website for the Occultum Tor Relays

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
